### ISSUE TITLE
make should honor source files in src folder

### ISSUE THREAD

**Issue by lotharschulz** [cloudflare/hellogopher#10]
I experienced the ```make``` command only working correctly if go source file(s) is/are located in root folder of a repository.

```make``` on [lotharschulz/gohello02@tag/0.0.1](https://github.com/lotharschulz/gohello02/releases/tag/0.0.1) worked correctly only because of https://github.com/lotharschulz/gohello02/commit/cc13b57d243618756e8a93d8b1153f1211aa82e4

**Comment by FiloSottile** [comment]
Hi! Thanks for trying hellogopher :)

Hellogopher is meant to work on projects that follow the conventional Go structure, which doesn't include a `src/` or `github.com/` subfolder.

However, code doesn't have to be in the project root. You can add the subpath like the `otherbin` target does.

However, that commit looks right: before, the name of your package was `github.com/lotharschulz/gohello02/src/github.com/lotharschulz/gohello02`.

**Comment by lotharschulz** [comment]
https://github.com/cloudflare/hellogopher/commit/3209e97ba67bc32758133989837f6f5f9117ceef clarifies things - thanks.

However according to https://golang.org/doc/code.html#Workspaces the conventional Go structure includes ```src```folders.

**Comment by FiloSottile** [comment]
That's correct, however the workspace refers to your system environment, not to the one you make inside the repository. The repository goes inside src, not the other way around.

Let me know if you can think of a wording to further clarify that.
