### ISSUE TITLE
Detect missing make setup call, or make it automatic

### ISSUE THREAD

**Issue by FiloSottile** [cloudflare/hellogopher#5]

**Comment by ghost** [comment]
I'd be interested in this. Mind if I give it a go? Just added hellogopher to my project :)

**Comment by FiloSottile** [comment]
Absolutely :) the simplest and least invasive it is, the most likely it will get turbo-merged.

**Comment by ghost** [comment]
Thanks!

I've made it complain if you haven't run it yet, thought perhaps the best solution was to add a ``.GOPATH/.setup`` dependency like you have with ``.GOPATH/.ok``
